export const TRENDING_TODAY_REQUEST = 'TRENDING_TODAY_REQUEST';
export const TRENDING_TODAY_SUCCESS = 'TRENDING_TODAY_SUCCESS';
export const TRENDING_TODAY_FAILURE = 'TRENDING_TODAY_FAILURE';

export const TRENDING_THIS_WEEK_REQUEST = 'TRENDING_THIS_WEEK_REQUEST';
export const TRENDING_THIS_WEEK_SUCCESS = 'TRENDING_THIS_WEEK_SUCCESS';
export const TRENDING_THIS_WEEK_FAILURE = 'TRENDING_THIS_WEEK_FAILURE';

export const POPULAR_TV_REQUEST = 'POPULAR_TV_REQUEST';
export const POPULAR_TV_SUCCESS = 'POPULAR_TV_SUCCESS';
export const POPULAR_TV_FAILURE = 'POPULAR_TV_FAILURE';

export const POPULAR_MOVIES_REQUEST = 'POPULAR_MOVIES_REQUEST';
export const POPULAR_MOVIES_SUCCESS = 'POPULAR_MOVIES_SUCCESS';
export const POPULAR_MOVIES_FAILURE = 'POPULAR_MOVIES_FAILURE';

export const FREE_MOVIES_REQUEST = 'FREE_MOVIES_REQUEST';
export const FREE_MOVIES_SUCCESS = 'FREE_MOVIES_SUCCESS';
export const FREE_MOVIES_FAILURE = 'FREE_MOVIES_FAILURE';

export const FREE_TV_REQUEST = 'FREE_TV_REQUEST';
export const FREE_TV_SUCCESS = 'FREE_TV_SUCCESS';
export const FREE_TV_FAILURE = 'FREE_TV_FAILURE';

export const TRAILERS_STREAMING_REQUEST = 'TRAILERS_STREAMING_REQUEST';
export const TRAILERS_STREAMING_SUCCESS = 'TRAILERS_STREAMING_SUCCESS';
export const TRAILERS_STREAMING_FAILURE = 'TRAILERS_STREAMING_FAILURE';

export const TRAILERS_TV_REQUEST = 'TRAILERS_TV_REQUEST';
export const TRAILERS_TV_SUCCESS = 'TRAILERS_TV_SUCCESS';
export const TRAILERS_TV_FAILURE = 'TRAILERS_TV_FAILURE';

export const TRAILERS_RENT_REQUEST = 'TRAILERS_RENT_REQUEST';
export const TRAILERS_RENT_SUCCESS = 'TRAILERS_RENT_SUCCESS';
export const TRAILERS_RENT_FAILURE = 'TRAILERS_RENT_FAILURE';

export const TRAILERS_THEATRES_REQUEST = 'TRAILERS_THEATRES_REQUEST';
export const TRAILERS_THEATRES_SUCCESS = 'TRAILERS_THEATRES_SUCCESS';
export const TRAILERS_THEATRES_FAILURE = 'TRAILERS_THEATRES_FAILURE';

// -------------------------------------- Movie/Show Details

export const ACTOR_DETAILS_REQUEST = 'ACTOR_DETAILS_REQUEST';
export const ACTOR_DETAILS_SUCCESS = 'ACTOR_DETAILS_SUCCESS';
export const ACTOR_DETAILS_FAILURE = 'ACTOR_DETAILS_FAILURE';

export const ACTOR_CREDITS_REQUEST = 'ACTOR_CREDITS_REQUEST';
export const ACTOR_CREDITS_SUCCESS = 'ACTOR_CREDITS_SUCCESS';
export const ACTOR_CREDITS_FAILURE = 'ACTOR_CREDITS_FAILURE';

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAILURE = 'MOVIE_DETAILS_FAILURE';

export const MOVIE_CAST_REQUEST = 'MOVIE_CAST_REQUEST';
export const MOVIE_CAST_SUCCESS = 'MOVIE_CAST_SUCCESS';
export const MOVIE_CAST_FAILURE = 'MOVIE_CAST_FAILURE';

export const MOVIE_KEYWORDS_REQUEST = 'MOVIE_KEYWORDS_REQUEST';
export const MOVIE_KEYWORDS_SUCCESS = 'MOVIE_KEYWORDS_SUCCESS';
export const MOVIE_KEYWORDS_FAILURE = 'MOVIE_KEYWORDS_FAILURE';

export const TV_DETAILS_REQUEST = 'TV_DETAILS_REQUEST';
export const TV_DETAILS_SUCCESS = 'TV_DETAILS_SUCCESS';
export const TV_DETAILS_FAILURE = 'TV_DETAILS_FAILURE';

export const TV_CAST_REQUEST = 'TV_CAST_REQUEST';
export const TV_CAST_SUCCESS = 'TV_CAST_SUCCESS';
export const TV_CAST_FAILURE = 'TV_CAST_FAILURE';

export const TV_KEYWORDS_REQUEST = 'TV_KEYWORDS_REQUEST';
export const TV_KEYWORDS_SUCCESS = 'TV_KEYWORDS_SUCCESS';
export const TV_KEYWORDS_FAILURE = 'TV_KEYWORDS_FAILURE';
