export const SEARCH_ALL_REQUEST = 'SEARCH_ALL_REQUEST';
export const SEARCH_ALL_SUCCESS = 'SEARCH_ALL_SUCCESS';
export const SEARCH_ALL_FAILURE = 'SEARCH_ALL_FAILURE';

export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';

export const SEARCH_TV_REQUEST = 'SEARCH_TV_REQUEST';
export const SEARCH_TV_SUCCESS = 'SEARCH_TV_SUCCESS';
export const SEARCH_TV_FAILURE = 'SEARCH_TV_FAILURE';

export const SEARCH_PEOPLE_REQUEST = 'SEARCH_PEOPLE_REQUEST';
export const SEARCH_PEOPLE_SUCCESS = 'SEARCH_PEOPLE_SUCCESS';
export const SEARCH_PEOPLE_FAILURE = 'SEARCH_PEOPLE_FAILURE';
