export const TV_ON_AIR_REQUEST = 'TV_ON_AIR_REQUEST';
export const TV_ON_AIR_SUCCESS = 'TV_ON_AIR_SUCCESS';
export const TV_ON_AIR_FAILURE = 'TV_ON_AIR_FAILURE';

export const TV_TRAILER_ONE_REQUEST = 'TV_TRAILER_ONE_REQUEST';
export const TV_TRAILER_ONE_SUCCESS = 'TV_TRAILER_ONE_SUCCESS';
export const TV_TRAILER_ONE_FAILURE = 'TV_TRAILER_ONE_FAILURE';

export const TV_TRAILER_TWO_REQUEST = 'TV_TRAILER_TWO_REQUEST';
export const TV_TRAILER_TWO_SUCCESS = 'TV_TRAILER_TWO_SUCCESS';
export const TV_TRAILER_TWO_FAILURE = 'TV_TRAILER_TWO_FAILURE';

export const TV_TRAILER_THREE_REQUEST = 'TV_TRAILER_THREE_REQUEST';
export const TV_TRAILER_THREE_SUCCESS = 'TV_TRAILER_THREE_SUCCESS';
export const TV_TRAILER_THREE_FAILURE = 'TV_TRAILER_THREE_FAILURE';

export const TV_TRAILER_FOUR_REQUEST = 'TV_TRAILER_FOUR_REQUEST';
export const TV_TRAILER_FOUR_SUCCESS = 'TV_TRAILER_FOUR_SUCCESS';
export const TV_TRAILER_FOUR_FAILURE = 'TV_TRAILER_FOUR_FAILURE';

export const TV_TRAILER_FIVE_REQUEST = 'TV_TRAILER_FIVE_REQUEST';
export const TV_TRAILER_FIVE_SUCCESS = 'TV_TRAILER_FIVE_SUCCESS';
export const TV_TRAILER_FIVE_FAILURE = 'TV_TRAILER_FIVE_FAILURE';

export const TV_TRAILER_SIX_REQUEST = 'TV_TRAILER_SIX_REQUEST';
export const TV_TRAILER_SIX_SUCCESS = 'TV_TRAILER_SIX_SUCCESS';
export const TV_TRAILER_SIX_FAILURE = 'TV_TRAILER_SIX_FAILURE';

export const TV_TRAILER_SEVEN_REQUEST = 'TV_TRAILER_SEVEN_REQUEST';
export const TV_TRAILER_SEVEN_SUCCESS = 'TV_TRAILER_SEVEN_SUCCESS';
export const TV_TRAILER_SEVEN_FAILURE = 'TV_TRAILER_SEVEN_FAILURE';

export const TV_TRAILER_EIGHT_REQUEST = 'TV_TRAILER_EIGHT_REQUEST';
export const TV_TRAILER_EIGHT_SUCCESS = 'TV_TRAILER_EIGHT_SUCCESS';
export const TV_TRAILER_EIGHT_FAILURE = 'TV_TRAILER_EIGHT_FAILURE';

export const TV_TRAILER_NINE_REQUEST = 'TV_TRAILER_NINE_REQUEST';
export const TV_TRAILER_NINE_SUCCESS = 'TV_TRAILER_NINE_SUCCESS';
export const TV_TRAILER_NINE_FAILURE = 'TV_TRAILER_NINE_FAILURE';
