export const TV_ON_AIR_REQUEST = 'TV_ON_AIR_REQUEST';
export const TV_ON_AIR_SUCCESS = 'TV_ON_AIR_SUCCESS';
export const TV_ON_AIR_FAILURE = 'TV_ON_AIR_FAILURE';

export const TV_TRAILER_ONE_REQUEST = 'TV_TRAILER_ONE_REQUEST';
export const TV_TRAILER_ONE_SUCCESS = 'TV_TRAILER_ONE_SUCCESS';
export const TV_TRAILER_ONE_FAILURE = 'TV_TRAILER_ONE_FAILURE';
